name: Build and deploy documentation
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v2.5.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-swagger-ui
          pip install mkdocs-swagger-ui-tag
          pip install mkdocs-table-reader-plugin
          pip install mkdocs-embed-external-markdown
      - name: Build and deploy
        run: |
          mkdocs build --clean
          mkdocs gh-deploy
      - name: Deployed
        run: echo "Deployed Successfully!"
